/** 设置margin和padding */
export class MarginPaddingModel {
  /** 上下左右margin */
  m?: number = 16
  /** 上下左右padding */
  p?: number = 16
  /** 上下margin */
  mtb?: number = 0
  /** 上下padding */
  ptb?: number = 0
  /** 左右margin */
  mlr?: number = 0
  /** 左右padding */
  plr?: number = 0
  /** 左margin */
  ml?: number = 0
  /** 右margin */
  mr?: number = 0
  /** 上margin */
  mt?: number = 0
  /** 下margin */
  mb?: number = 0
  /** 左padding */
  pl?: number = 0
  /** 右padding */
  pr?: number = 0
  /** 上padding */
  pt?: number = 0
  /** 下padding */
  pb?: number = 0
}